# Generated by Django 4.2.2 on 2023-07-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNomads', '0003_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='imagen',
        ),
    ]
